openapi: 3.0.0
info:
  title: httpbin-endpoint
  description: oas for the kube deployment of httpbin
  version: 1.0.0

servers:
  - url: http://httpbin.kong-dp.svc.cluster.local:8000

x-kong-name: httpbin-endpoint
x-kong-tag: [ "demo", "httpbin" ]

paths:
  '/httpbin':
    get: